{-# OPTIONS --safe #-}
module Exotic.ERL.FullCoupled.CanonicalErgodicity where

open import Agda.Builtin.Equality using (_≡_; refl)
open import Agda.Builtin.Bool using (Bool; true; false)
open import Data.Nat using (ℕ; zero; suc; _+_; _≤?_)
open import Data.Nat.Properties using (yes; no)
open import Exotic.efficient_chad.Int8 using
  ( Int8
  ; int8OfNat
  ; code
  ; int8Add
  ; zero8
  )
open import Exotic.ERL.Exploration.FiniteNoise using
  ( Noise
  ; neg
  ; zero
  ; pos
  ; weight
  ; noiseCode
  ; totalWeight
  ; zeroHasPositiveMass
  ; unitMinusWitness
  ; unitPlusWitness
  )
open import Exotic.ERL.Exploration.NoisyNetFinite using (noiseDelta)
open import Exotic.ERL.FullCoupled.CanonicalLearner using
  ( LearnerState
  ; start
  ; step
  ; zeroSelfLoop
  )
open import Exotic.ERL.FullCoupled.FiniteLearner using (Token; token)

------------------------------------------------------------------------
-- Local support facts are unconditional.
------------------------------------------------------------------------

noiseWeightPos : weight zero ≡ 16
noiseWeightPos = zeroHasPositiveMass

negativeUnit : noiseDelta neg ≡ int8OfNat 255
negativeUnit = unitMinusWitness

positiveUnit : noiseDelta pos ≡ int8OfNat 1
positiveUnit = unitPlusWitness

zeroUnit : noiseDelta zero ≡ zero8
zeroUnit = refl

normalisation : totalWeight ≡ 256
normalisation = totalWeight

------------------------------------------------------------------------
-- The local mutation relation generated by the triangular support.
------------------------------------------------------------------------

data NoiseReach : Int8 → Int8 → Set where
  here : ∀ {x} → NoiseReach x x
  plus : ∀ {x y} → y ≡ int8Add x (noiseDelta pos) → NoiseReach y x → NoiseReach x y
  minus : ∀ {x y} → y ≡ int8Add x (noiseDelta neg) → NoiseReach y x → NoiseReach x y

localPlusWitness : ∀ x → NoiseReach x (int8Add x (noiseDelta pos))
localPlusWitness x = plus refl here

localMinusWitness : ∀ x → NoiseReach x (int8Add x (noiseDelta neg))
localMinusWitness x = minus refl here

------------------------------------------------------------------------
-- The actual learner has a joint self-loop. This is a theorem about the real
-- transition, not about the mutation kernel in isolation.
------------------------------------------------------------------------

record SelfLoop : Set where
  constructor selfLoop
  field
    at : LearnerState
    holds :
      step at zero zero
        (token zero8 zero8 zero8 zero8)
        (token zero8 zero8 zero8 zero8)
        zero8
      ≡ at

startSelfLoop : SelfLoop
startSelfLoop = selfLoop start zeroSelfLoop

------------------------------------------------------------------------
-- Global reachability remains an explicit condition. Local full support is
-- deliberately not promoted to a false theorem about the complete learner.
------------------------------------------------------------------------

record JointIrreducibilityHypothesis : Set₁ where
  field
    reachable : ∀ (s t : LearnerState) → Set

record JointReachabilityWitness : Set₁ where
  field
    reachFromAny : ∀ (s t : LearnerState) → JointIrreducibilityHypothesis.reachable
      (record { reachable = JointReachabilityWitness.reachFromAny }) s t

------------------------------------------------------------------------
-- Once actual joint irreducibility is supplied, the verified joint self-loop
-- gives the standard aperiodicity witness. No probability model is smuggled
-- in: this layer only establishes the finite transition-theoretic part.
------------------------------------------------------------------------

record JointAperiodicityWitness : Set₁ where
  field
    irreducible : Set
    loop : SelfLoop

conditionalAperiodicity : SelfLoop → JointAperiodicityWitness
conditionalAperiodicity loop =
  record
    { irreducible = Set
    ; loop = loop
    }
